"""empty message

Revision ID: 4fb57650f1a1
Revises: a1dbdef68ee3
Create Date: 2019-06-23 11:34:16.882621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb57650f1a1'
down_revision = 'a1dbdef68ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('meal_item_orders_meal_item_id_fkey'), 'meal_item_orders', 'meal_items', ['meal_item_id'], ['id'])
    op.create_foreign_key(op.f('meal_item_orders_order_id_fkey'), 'meal_item_orders', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('meal_items_location_id_fkey'), 'meal_items', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('meal_services_session_id_fkey'), 'meal_services', 'meal_sessions', ['session_id'], ['id'])
    op.create_foreign_key(op.f('meal_services_user_id_fkey'), 'meal_services', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('meal_sessions_location_id_fkey'), 'meal_sessions', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('menus_main_meal_id_fkey'), 'menus', 'meal_items', ['main_meal_id'], ['id'])
    op.create_foreign_key(op.f('menus_location_id_fkey'), 'menus', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('menus_vendor_engagement_id_fkey'), 'menus', 'vendor_engagements', ['vendor_engagement_id'], ['id'])
    op.create_foreign_key(op.f('orders_location_id_fkey'), 'orders', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('orders_menu_id_fkey'), 'orders', 'menus', ['menu_id'], ['id'])
    op.create_foreign_key(op.f('permissions_role_id_fkey'), 'permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('user_roles_location_id_fkey'), 'user_roles', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('users_user_type_id_fkey'), 'users', 'user_roles', ['user_type_id'], ['id'])
    op.create_foreign_key(op.f('vendor_engagements_vendor_id_fkey'), 'vendor_engagements', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(op.f('vendor_engagements_location_id_fkey'), 'vendor_engagements', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('vendor_ratings_engagement_id_fkey'), 'vendor_ratings', 'vendor_engagements', ['engagement_id'], ['id'])
    op.create_foreign_key(op.f('vendor_ratings_main_meal_id_fkey'), 'vendor_ratings', 'meal_items', ['main_meal_id'], ['id'])
    op.create_foreign_key(op.f('vendor_ratings_vendor_id_fkey'), 'vendor_ratings', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(op.f('vendors_location_id_fkey'), 'vendors', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vendors_location_id_fkey'), 'vendors', type_='foreignkey')
    op.drop_constraint(op.f('vendor_ratings_vendor_id_fkey'), 'vendor_ratings', type_='foreignkey')
    op.drop_constraint(op.f('vendor_ratings_main_meal_id_fkey'), 'vendor_ratings', type_='foreignkey')
    op.drop_constraint(op.f('vendor_ratings_engagement_id_fkey'), 'vendor_ratings', type_='foreignkey')
    op.drop_constraint(op.f('vendor_engagements_location_id_fkey'), 'vendor_engagements', type_='foreignkey')
    op.drop_constraint(op.f('vendor_engagements_vendor_id_fkey'), 'vendor_engagements', type_='foreignkey')
    op.drop_constraint(op.f('users_user_type_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_location_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('permissions_role_id_fkey'), 'permissions', type_='foreignkey')
    op.drop_constraint(op.f('orders_menu_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_location_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('menus_vendor_engagement_id_fkey'), 'menus', type_='foreignkey')
    op.drop_constraint(op.f('menus_location_id_fkey'), 'menus', type_='foreignkey')
    op.drop_constraint(op.f('menus_main_meal_id_fkey'), 'menus', type_='foreignkey')
    op.drop_constraint(op.f('meal_sessions_location_id_fkey'), 'meal_sessions', type_='foreignkey')
    op.drop_constraint(op.f('meal_services_user_id_fkey'), 'meal_services', type_='foreignkey')
    op.drop_constraint(op.f('meal_services_session_id_fkey'), 'meal_services', type_='foreignkey')
    op.drop_constraint(op.f('meal_items_location_id_fkey'), 'meal_items', type_='foreignkey')
    op.drop_constraint(op.f('meal_item_orders_order_id_fkey'), 'meal_item_orders', type_='foreignkey')
    op.drop_constraint(op.f('meal_item_orders_meal_item_id_fkey'), 'meal_item_orders', type_='foreignkey')
    # ### end Alembic commands ###
