"""empty message

Revision ID: a1dbdef68ee3
Revises: 1de0b9014901
Create Date: 2019-06-23 11:31:28.897829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1dbdef68ee3'
down_revision = '1de0b9014901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abouts', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('activities', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('faqs', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('locations', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('meal_item_orders', 'meal_item_id',
                    existing_type=sa.SMALLINT(),
                    type_=sa.String(length=80),
                    existing_nullable=False)
    op.alter_column('meal_item_orders', 'order_id',
                    existing_type=sa.SMALLINT(),
                    type_=sa.String(length=80),
                    existing_nullable=False)
    op.alter_column('meal_items', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('meal_items', 'location_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('meal_services', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('meal_services', 'session_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=False)
    op.alter_column('meal_services', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=False)
    op.alter_column('meal_sessions', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('meal_sessions', 'location_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('menus', 'allowed_protein',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('menus', 'allowed_side',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('menus', 'date',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.Date(),
                    existing_nullable=False)
    op.alter_column('menus', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('menus', 'location_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('menus', 'main_meal_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=False)
    op.alter_column('menus', 'vendor_engagement_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('orders', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('orders', 'location_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('orders', 'menu_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('permissions', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('permissions', 'role_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('roles', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('user_roles', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('user_roles', 'location_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('user_roles', 'role_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('users', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('users', 'user_type_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('vendor_engagements', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('vendor_engagements', 'location_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('vendor_engagements', 'vendor_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('vendor_ratings', 'engagement_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('vendor_ratings', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('vendor_ratings', 'main_meal_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('vendor_ratings', 'vendor_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    op.alter_column('vendors', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80))
    op.alter_column('vendors', 'location_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=80),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'location_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('vendors', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('vendor_ratings', 'vendor_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('vendor_ratings', 'main_meal_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('vendor_ratings', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('vendor_ratings', 'engagement_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('vendor_engagements', 'vendor_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('vendor_engagements', 'location_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('vendor_engagements', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('users', 'user_type_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('users', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('user_roles', 'role_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('user_roles', 'location_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('user_roles', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('roles', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('permissions', 'role_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('permissions', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('orders', 'menu_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('orders', 'location_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('orders', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('menus', 'vendor_engagement_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('menus', 'main_meal_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('menus', 'location_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('menus', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('menus', 'date',
                    existing_type=sa.Date(),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False)
    op.alter_column('menus', 'allowed_side',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('menus', 'allowed_protein',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('meal_sessions', 'location_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('meal_sessions', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('meal_services', 'user_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('meal_services', 'session_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('meal_services', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('meal_items', 'location_id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('meal_items', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('meal_item_orders', 'order_id',
                    existing_type=sa.String(length=80),
                    type_=sa.SMALLINT(),
                    existing_nullable=False)
    op.alter_column('meal_item_orders', 'meal_item_id',
                    existing_type=sa.String(length=80),
                    type_=sa.SMALLINT(),
                    existing_nullable=False)
    op.alter_column('locations', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('faqs', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('activities', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    op.alter_column('abouts', 'id',
                    existing_type=sa.String(length=80),
                    type_=sa.INTEGER())
    # ### end Alembic commands ###
